import type { CallOption, CallQuestion, Tradeoff } from "./callModel";

const pass = (merit: string, risk: string, valuePlan: string): Tradeoff => ({ merit, risk, valuePlan });
const pon = (tile: CallOption["discard"], discard: CallOption["discard"], merit: string, risk: string, valuePlan: string): CallOption => ({ action: "pon", consumed: [tile, tile], discard, merit, risk, valuePlan });
const chi = (consumed: CallOption["consumed"], discard: CallOption["discard"], merit: string, risk: string, valuePlan: string): CallOption => ({ action: "chi", consumed, discard, merit, risk, valuePlan });
const question = (data: Pick<CallQuestion, "id" | "difficulty" | "category" | "title" | "hand" | "offered" | "options" | "pass" | "recommendedAction" | "explanation" | "checkpoint"> & Partial<CallQuestion>): CallQuestion => ({ roundWind: "東", roundNumber: 2, seatWind: "南", turn: 7, scores: [25000, 25000, 25000, 25000], doraIndicator: "8s", offeredBy: "kamicha", confidence: "high", context: "4人打ち・喰いタンあり・喰い替えなし。赤牌・本場・供託なし。誰もリーチしていません。", ...data });

// Original teaching positions, not scraped game records. Recommendations are editorial judgments.
export const callQuestions: readonly CallQuestion[] = [
  question({ id: "b-white-tenpai", difficulty: "beginner", category: "yakuhai", title: "役を作って両面テンパイ", hand: "456m34588p45s白白中", offered: "白", offeredBy: "toimen", turn: 9,
    options: [pon("白", "中", "白の役を確保し、両面テンパイに進めます。", "リーチはできなくなり、守備に使える手牌も減ります。", "白1翻。アガリ牌ごとの実点数は下で確認できます。")],
    pass: pass("門前を保ち、リーチで打点を上げられます。", "白がもう一度出る保証はなく、テンパイが遅れます。", "白とリーチを狙えますが、まだテンパイしていません。"), recommendedAction: "pon",
    explanation: "9巡目で白をポンすると、中を切って3索・6索待ちになります。今回は打点条件や他家のリーチがなく、役付き両面テンパイの速度を優先します。", checkpoint: "役ができることと、鳴いた後の待ちを一緒に確認します。" }),
  question({ id: "b-tanyao", difficulty: "beginner", category: "speed", title: "端牌を外してタンヤオ", hand: "2349m45677p4588s", offered: "6s", turn: 10,
    options: [chi(["4s", "5s"], "9m", "9萬を外し、タンヤオのテンパイになります。", "7筒・8索のシャンポン待ちに固定されます。", "すべて2〜8の牌なので、喰いタンが成立します。")],
    pass: pass("門前リーチと待ちの改善を残せます。", "10巡目からもう一度テンパイする牌が必要です。", "タンヤオ・リーチを狙う門前手です。"), recommendedAction: "chi",
    explanation: "6索をチーして9萬を切ると、タンヤオがある7筒・8索待ちです。両面ではありませんが、10巡目の平場でテンパイを取る価値があります。", checkpoint: "端牌を切った後、全ての牌が2〜8か確認します。" }),
  question({ id: "b-no-yaku", difficulty: "beginner", category: "noYaku", title: "形ができても役がない", hand: "1239m45688p45s西西", offered: "6s",
    options: [chi(["4s", "5s"], "9m", "形の上ではテンパイします。", "西は役牌ではなく、今の待ちでは通常のロンもツモも役がありません。", "ドラだけでは役になりません。形だけのテンパイです。")],
    pass: pass("門前リーチというアガリ役を残せます。", "もう一枚、テンパイへ進む牌を引く必要があります。", "リーチ、または門前ツモの役を残します。"), recommendedAction: "pass",
    explanation: "東場の南家なので西は役牌ではありません。123萬があるためタンヤオもなく、チーすると門前役が消えます。今回は役なしの仕掛けを避けます。", checkpoint: "ドラがあっても、別にアガリ役が必要です。" }),
  question({ id: "b-honitsu", difficulty: "beginner", category: "value", title: "ホンイツと白を両立", hand: "1234569m東東白白北北", offered: "白", offeredBy: "shimocha", turn: 10,
    options: [pon("白", "9m", "白とホンイツがあるテンパイを取れます。", "門前ホンイツの3翻とリーチは失います。", "ホンイツ2翻・白1翻が残る仕掛けです。")],
    pass: pass("門前ホンイツの高い打点を残せます。", "10巡目から手を完成させる必要があります。", "門前ホンイツ3翻に白・リーチを加える余地があります。"), recommendedAction: "pon",
    explanation: "白をポンし9萬を外せば、一色と字牌だけの役付きテンパイです。10巡目でも安い役牌だけの手にはならず、速度と打点を両立できます。", checkpoint: "ホンイツは鳴いても2翻残ります。" }),
  question({ id: "b-ittsu", difficulty: "beginner", category: "speed", title: "一気通貫を完成させるチー", hand: "12456789m55p79s東", offered: "3m", turn: 11, doraIndicator: "1p",
    options: [chi(["1m", "2m"], "東", "123・456・789萬がそろい、8索待ちに進めます。", "一気通貫は食い下がりで1翻になり、待ちはカンチャンです。", "一気通貫1翻が成立するテンパイです。")],
    pass: pass("門前の一気通貫2翻とリーチを残します。", "終盤に向けてテンパイ機会を一つ逃します。", "門前一通の打点は高い一方、まだ未完成です。"), recommendedAction: "chi",
    explanation: "11巡目なので、3萬をチーして東を切り、一気通貫のテンパイを取る方を推奨します。8索だけの待ちであることと食い下がりを忘れないでください。", checkpoint: "一通は123・456・789の3組が同じ色で必要です。" }),
  question({ id: "b-sanshoku", difficulty: "beginner", category: "value", title: "三色だけに頼らない仕掛け", hand: "23567m23466p45s東", offered: "4m", turn: 10,
    options: [chi(["2m", "3m"], "東", "3索なら三色、6索でもタンヤオでアガれるテンパイです。", "三色の食い下がりがあり、待ち牌によって打点が違います。", "タンヤオ1翻。3索アガリでは三色同順1翻も付きます。")],
    pass: pass("門前三色2翻とリーチを残せます。", "両面テンパイを今すぐ取る機会を逃します。", "門前三色の高打点を狙えますが、アガリ牌次第です。"), recommendedAction: "chi",
    explanation: "4萬をチーして東を切ると3索・6索待ちです。3索だけを三色の当たりと誤解しないこと。6索でもタンヤオがあるため、両方でアガれます。", checkpoint: "役が付くアガリ牌と、打点が上がるアガリ牌を分けます。" }),
  question({ id: "b-seven-pairs", difficulty: "beginner", category: "pairs", title: "七対子テンパイを崩さない", hand: "1144m2277p3388s東", offered: "1m", offeredBy: "toimen",
    options: [pon("1m", "東", "対々和へ向かう一つ目の刻子を作れます。", "完成目前の七対子を失い、残りの対子も刻子にする必要があります。", "対々和2翻はまだ未確定です。")],
    pass: pass("東待ちの七対子テンパイを維持します。", "東は単騎待ちで、広い待ちではありません。", "七対子2翻がすでにあり、リーチも選べます。"), recommendedAction: "pass",
    explanation: "今は六つの対子と東1枚で、七対子のテンパイです。1萬をポンすると七対子が消え、対々和を一から完成させる必要があります。", checkpoint: "対子が多いときは通常形だけでなく七対子も確認します。" }),
  question({ id: "b-green-last", difficulty: "beginner", category: "speed", title: "終盤は役牌でテンパイを取る", hand: "123m456p678s發發西北", offered: "發", offeredBy: "shimocha", turn: 13,
    options: [pon("發", "北", "發を確保し、西単騎のテンパイを取れます。", "西1種類の待ちで、手牌の入れ替え余地が減ります。", "發1翻。単騎待ちの符も計算に入ります。")],
    pass: pass("西・北の安全牌候補を残せます。", "13巡目でテンパイの機会を逃します。", "門前リーチを残しますが、残り巡目は少なくなっています。"), recommendedAction: "pon",
    explanation: "13巡目で他家のリーチがない平場です。發をポンして北を切り、役付きテンパイを取ります。単騎待ちだからといって、終盤のテンパイを常に捨てるわけではありません。", checkpoint: "終盤は役・待ち・残り巡目をまとめて見ます。" }),
  question({ id: "b-second-call", difficulty: "beginner", category: "speed", title: "一副露から両面テンパイへ", hand: "234m5688p45s東", melds: [{ kind: "pon", tiles: ["白", "白", "白"] }], offered: "7p", turn: 9,
    options: [chi(["5p", "6p"], "東", "すでにある白の役を使い、両面テンパイへ進めます。", "二副露になるため、残り手牌は7枚になります。", "白1翻はすでに成立。チーで役は消えません。")],
    pass: pass("二副露にせず、手牌の柔軟性を保てます。", "リーチはすでにできないので、門前維持の加点はありません。", "スルーしても白の役はありますが、リーチはできません。"), recommendedAction: "chi",
    explanation: "白をすでにポンしているため、スルーしてもリーチは戻りません。7筒をチーして東を切れば3索・6索待ち。今回は二副露の負担よりテンパイを優先します。", checkpoint: "一副露と門前では、スルーのメリットが違います。" }),
  question({ id: "b-double-east", difficulty: "beginner", category: "yakuhai", title: "親のダブ東を確保", hand: "456m34588p45s東東中", offered: "東", seatWind: "東", turn: 8,
    options: [pon("東", "中", "場風と自風を兼ねる東で2翻を確保し、テンパイします。", "門前リーチの追加打点を失います。", "東は場風1翻・自風1翻の合計2翻です。")],
    pass: pass("リーチを加えた門前手の打点を残せます。", "親の両面テンパイを今すぐ取る機会を逃します。", "ダブ東を暗刻にしてリーチする余地があります。"), recommendedAction: "pon",
    explanation: "東場の東家なので、東をポンすると2翻が残ります。中を切れば両面テンパイです。親で連荘を目指せる、役と待ちの両方がある仕掛けを推奨します。", checkpoint: "親だから何でも鳴くのではなく、役と待ちがそろっているか見ます。" }),

  question({ id: "m-white-early", difficulty: "intermediate", category: "value", title: "序盤は門前の打点を残す", hand: "456m34588p45s白白中", offered: "白", offeredBy: "toimen", turn: 3, doraIndicator: "7p", confidence: "medium",
    options: [pon("白", "中", "ドラ2枚を残した両面テンパイで、十分な攻撃手になります。", "リーチを加えた満貫級の門前手は失います。", "白・ドラ2の3翻があるテンパイです。")],
    pass: pass("ドラ2枚と白にリーチを加える高打点の余地を残します。", "白を鳴いて即テンパイする機会を逃します。", "白・ドラ2・リーチの4翻を狙えます。符により満貫になる場合があります。"), recommendedAction: "pass",
    explanation: "まだ3巡目で、リーチを受けておらず打点が欲しい平場です。ここではドラ2枚を使った門前手を育てるスルー寄りとします。ただしポンの両面テンパイも有力で、唯一の正解ではありません。", checkpoint: "序盤の時間と、門前で増やせる翻数を比べます。" }),
  question({ id: "m-white-late", difficulty: "intermediate", category: "speed", title: "同じ牌姿でも巡目で変わる", hand: "456m34588p45s白白中", offered: "白", offeredBy: "toimen", turn: 11, doraIndicator: "7p",
    options: [pon("白", "中", "ドラ2枚の打点を残し、11巡目に両面テンパイを取れます。", "リーチの1翻と裏ドラの可能性は失います。", "白・ドラ2の3翻。安い役牌のみの仕掛けではありません。")],
    pass: pass("リーチを加える高打点の余地を残します。", "残り巡目が減り、未テンパイのまま終わる可能性があります。", "門前で4翻以上を目指すには、まずテンパイが必要です。"), recommendedAction: "pon",
    explanation: "序盤例と同じ手牌ですが、今は11巡目です。すでにドラ2枚があり、白をポンしても打点を保てるので、今回は両面テンパイを取る方を推奨します。", checkpoint: "牌姿だけでなく、判断した巡目もセットで覚えます。" }),
  question({ id: "m-narrow-tenpai", difficulty: "intermediate", category: "shape", title: "単騎テンパイを急がない", hand: "234m345678p468s北", offered: "7s", turn: 3, confidence: "medium",
    options: [chi(["6s", "8s"], "北", "タンヤオの4索単騎テンパイになります。", "雀頭のない手から、待ちを4索1種類に固定します。", "タンヤオ1翻の単騎待ちです。")],
    pass: pass("468索の使い直しと、門前リーチの価値を残します。", "今すぐのテンパイは取れません。", "タンヤオとリーチを狙い、待ちの広いテンパイを目指します。"), recommendedAction: "pass",
    explanation: "7索を678でチーし北を切ると、4索単騎になります。3巡目なら、その狭いテンパイに急がず門前の変化を残す方を推奨します。チーも合法で、速度を優先する立場なら候補です。", checkpoint: "鳴いた後の待ちを作り、雀頭がどこにできるか見ます。" }),
  question({ id: "m-ukeire-loss", difficulty: "intermediate", category: "shape", title: "シャンテンが進まないチー", hand: "234m34567p468s北北", offered: "4p", turn: 4,
    options: [chi(["3p", "5p"], "8s", "345筒の完成面子を副露として固定できます。", "シャンテンを進めず、残る4筒の使い道が減ります。北が残りタンヤオも未確定です。", "北の対子を処理してタンヤオなどを作る必要があります。")],
    pass: pass("筒子の連続形を門前で使い直せます。", "鳴いて面子を固定する機会は見送ります。", "リーチを軸に、北を雀頭として残す選択もできます。"), recommendedAction: "pass",
    explanation: "345筒をチーして8索を切る比較では、進行度が良くならず、受け入れの柔軟性が失われます。序盤に役も確定しないためスルーを推奨します。別のチー形でも、鳴いた後に役と打牌を確認する必要があります。", checkpoint: "鳴く前後を同じ13枚相当で比べます。" }),
  question({ id: "m-honitsu-development", difficulty: "intermediate", category: "value", title: "ホンイツを役牌から進める", hand: "223456778p白白發發", offered: "發", offeredBy: "shimocha", turn: 8,
    options: [pon("發", "8p", "發を確保し、白のポンも使える染め手へ進めます。", "門前ホンイツの1翻分とリーチを失います。", "發1翻を確保。ホンイツ2翻、白1翻は完成形次第です。")],
    pass: pass("門前ホンイツの高い翻数を残します。", "字牌対子が二つあり、どちらも重ならないと遅れやすい手です。", "ホンイツと役牌を門前で完成させる高打点を狙います。"), recommendedAction: "pon",
    explanation: "8巡目で、発のポンは役を確保しながらホンイツを進める仕掛けです。まだ完成ではありませんが、白も鳴いて使えるため、門前に固執せず進める方を推奨します。", checkpoint: "染め手の色と字牌の役を別々に確認します。" }),
  question({ id: "m-toitoi", difficulty: "intermediate", category: "pairs", title: "暗刻がある対々和を仕掛ける", hand: "11177m22p888s中中北", offered: "7m", offeredBy: "toimen",
    options: [pon("7m", "北", "暗刻2組にポン1組が加わり、対々和のテンパイになります。", "シャンポン待ちで、どちらの対子も鳴いて待ちは増やせません。", "対々和2翻。中でアガれば役牌も付きます。")],
    pass: pass("門前の三暗刻・リーチを狙えます。", "対々和のテンパイへ進む機会を逃します。", "門前の刻子手の加点は、完成形とアガリ方次第です。"), recommendedAction: "pon",
    explanation: "七対子は対子の種類が足りず、111萬と888索という暗刻がすでにあります。7萬をポンして北を切れば対々和テンパイなので、対子手だから常に七対子を優先するわけではありません。", checkpoint: "対子の種類数と、すでにある暗刻を数えます。" }),
  question({ id: "m-pairs-one-away", difficulty: "intermediate", category: "pairs", title: "七対子一向聴からのポン", hand: "1144m2277p3389s東", offered: "4m", offeredBy: "shimocha", turn: 4, doraIndicator: "8m",
    options: [pon("4m", "東", "4萬の刻子を作り、対々和方面へ切り替えられます。", "五つの対子を生かす七対子が消え、通常形を作り直します。", "対々和を目指せますが、まだ役は成立していません。")],
    pass: pass("七対子一向聴と門前リーチを残します。", "8索・9索・東の重なりを待つ必要があります。", "七対子2翻にリーチやドラを加える計画を残します。"), recommendedAction: "pass",
    explanation: "五つの対子があり、4巡目の七対子一向聴です。4萬をポンしても一気にテンパイするわけではないため、ここでは門前の対子手を維持します。", checkpoint: "七対子のシャンテンと、ポン後の通常形を直接比較します。" }),
  question({ id: "m-honitsu-closed", difficulty: "intermediate", category: "value", title: "完成面子を使うチーの代償", hand: "1234568m東東白白北北", offered: "7m", turn: 3, confidence: "medium",
    options: [chi(["6m", "8m"], "北", "678萬を確保してホンイツへ進めます。", "456萬の完成面子をほどき、門前ホンイツの翻数も失います。", "ホンイツ2翻を目指します。白の刻子もまだ必要です。")],
    pass: pass("123萬・456萬を保ち、門前ホンイツの打点を残します。", "今出た7萬を使って形を固定する機会を逃します。", "門前ホンイツ3翻を軸に白やリーチを狙えます。"), recommendedAction: "pass",
    explanation: "まだ3巡目で、7萬を678でチーすると456萬を崩す形になります。今回は完成面子と門前の打点を残すスルー寄りです。染め手だから全てのチーを急ぐ必要はありません。", checkpoint: "鳴いて得る面子だけでなく、失う面子も見ます。" }),
  question({ id: "m-already-open", difficulty: "intermediate", category: "speed", title: "すでに鳴いた手の速度", hand: "234m5688p45s東", melds: [{ kind: "pon", tiles: ["白", "白", "白"] }], offered: "4p", turn: 12,
    options: [chi(["5p", "6p"], "東", "白の役を保ち、両面テンパイを取ります。", "手牌が7枚になり、押し返された後の選択肢が減ります。", "白1翻があるテンパイ。456筒の面子自体は役ではありません。")],
    pass: pass("東を含む手牌を残して守備に備えられます。", "12巡目で、一向聴のまま手番を待ちます。", "門前役はすでに消えているため、リーチの加点はありません。"), recommendedAction: "chi",
    explanation: "白をすでに鳴いている12巡目の手です。4筒をチーして東を切れば両面テンパイになり、他家リーチもないため速度を優先します。", checkpoint: "スルーで何の価値が残るのかを具体的に挙げます。" }),
  question({ id: "m-nonvalue-wind", difficulty: "intermediate", category: "noYaku", title: "オタ風をポンする前に", hand: "456m34588p45s西西中", offered: "西", offeredBy: "toimen",
    options: [pon("西", "中", "形だけなら両面テンパイになります。", "西は自風でも場風でもなく、タンヤオも成立しません。", "この完成形では役なし。ドラがあってもアガれません。")],
    pass: pass("リーチという役と門前ツモを残します。", "今すぐ面子を完成させることはできません。", "リーチを使った門前手を狙います。"), recommendedAction: "pass",
    explanation: "東場の南家なので、西のポンには役牌が付きません。数牌が中張牌でも、西の刻子がある以上タンヤオにもならないため、今回はスルーします。", checkpoint: "字牌は三元牌か、自風・場風かを確認します。" }),

  question({ id: "a-top-close", difficulty: "advanced", category: "speed", title: "トップのオーラスで局を終える", hand: "456m34588p45s白白中", offered: "白", offeredBy: "toimen", roundWind: "南", roundNumber: 4, seatWind: "西", turn: 8, scores: [30000, 22000, 34000, 14000],
    context: "南4局、0本場・供託なし。自分は西家のトップ。喰いタンあり・赤牌なし。誰もリーチしていません。子の自分がアガれば対局終了の条件です。",
    options: [pon("白", "中", "小さなアガリでもトップのまま対局を終えられます。", "門前の加点は失いますが、今回は打点を増やす必要が小さい局面です。", "白1翻のアガリでトップを維持できます。")],
    pass: pass("リーチを加えて打点を伸ばせます。", "テンパイを遅らせ、他家の逆転機会を残します。", "高いアガリの追加価値より、今は局消化の価値が大きい条件です。"), recommendedAction: "pon",
    explanation: "子のトップで、アガれば終了するオーラスです。白をポンした両面テンパイなら安くても目的を果たせるため、速度を優先します。点棒だけでなく、待ちと役があることも確認しています。", checkpoint: "アガリ終了のルールと、自分が親か子かを確認します。" }),
  question({ id: "a-need-mangan", difficulty: "advanced", category: "value", title: "逆転に必要な打点を残す", hand: "1234569m東東白白北北", offered: "白", offeredBy: "shimocha", roundWind: "南", roundNumber: 4, seatWind: "西", turn: 4, scores: [35000, 25000, 20000, 20000], confidence: "medium",
    context: "南4局、0本場・供託なし。自分は西家20,000点、トップの東家35,000点。トップを目指す条件では満貫の東家直撃で逆転。赤牌なし、リーチなし。",
    options: [pon("白", "9m", "ホンイツと白のテンパイを今すぐ取れます。", "今の3翻の完成形では、トップとの差15,000点を直撃でも埋められません。", "ホンイツ・白の3翻。次の待ち替えや加点が必要です。")],
    pass: pass("門前ホンイツ・白・リーチの5翻を狙い、満貫直撃を残します。", "4巡目でも、まだテンパイする牌を待つ必要があります。", "門前ホンイツ3翻・白1翻・リーチ1翻で満貫を狙います。"), recommendedAction: "pass",
    explanation: "今回はラス回避ではなくトップを狙う条件です。満貫を東家からロンすると自分28,000点・東家27,000点になり逆転できます。白をポンした現在の形では打点が不足するため、序盤は門前の5翻を残します。", checkpoint: "同じ点差でも直撃とツモでは条件が違います。" }),
  question({ id: "a-defense", difficulty: "advanced", category: "defense", title: "リーチに対して打牌まで考える", hand: "2349m45677p4588s", offered: "6s", roundWind: "南", roundNumber: 3, turn: 10, scores: [25000, 35000, 23000, 16000], riichiBy: "toimen", riichiSticks: 1, rivers: { toimen: ["1p", "9p", "2m", "5m"] }, confidence: "medium",
    context: "南3局、自分は南家のトップ。対面がリーチ。河は判断に関係する公開牌のみを抜粋。赤牌・本場なし、供託1本。",
    options: [chi(["4s", "5s"], "9m", "タンヤオのテンパイには進めます。", "切る9萬はリーチ者の現物ではなく、安い手で押す負担があります。", "タンヤオ1翻のシャンポン待ちです。")],
    pass: pass("対面の現物2萬を残し、守備へ移る選択ができます。", "自分のアガリ機会は弱くなります。", "門前の加点より、今回はトップの点棒を守る方を優先します。"), recommendedAction: "pass",
    explanation: "チーすればテンパイですが、切る9萬は現物ではありません。トップの南3局で安いシャンポン手なので、ここではスルーして2萬の現物を使う守備寄りの判断を推奨します。9萬の危険度を確率で断定しているわけではありません。", checkpoint: "鳴ける牌より先に、鳴いた直後に何を切るかを見ます。" }),
  question({ id: "a-safe-discard", difficulty: "advanced", category: "defense", title: "現物を切って高打点テンパイ", hand: "456m34588p45s白白中", offered: "白", offeredBy: "shimocha", roundWind: "南", roundNumber: 2, turn: 9, scores: [25000, 25000, 25000, 24000], doraIndicator: "7p", riichiBy: "toimen", riichiSticks: 1, rivers: { toimen: ["1m", "9p", "中", "5p"] }, confidence: "medium",
    context: "対面がリーチ。自分は25,000点の南家。河は抜粋。白は下家から出ました。赤牌・本場なし、供託1本。",
    options: [pon("白", "中", "直後の中は現物で、白・ドラ2の両面テンパイを取れます。", "次に引く危険牌まで安全になるわけではなく、その都度押し引きが必要です。", "白・ドラ2の3翻がある両面待ちです。")],
    pass: pass("中の現物を保持し、守備の選択肢を残せます。", "打点があるテンパイ機会を逃します。", "門前の高打点を残す一方、今はリーチに追いついていません。"), recommendedAction: "pon",
    explanation: "この例は中を現物として切れ、ドラ2枚の両面テンパイになります。安い愚形で押す例と分けて、今回はポン寄りとします。ただし今後の押し返しを約束する判断ではありません。", checkpoint: "現物はそのリーチ者に対して安全で、他家全員の安全牌とは限りません。" }),
  question({ id: "a-dead-waits", difficulty: "advanced", category: "shape", title: "待ちが全て見えているテンパイ", hand: "2349m45677p4588s", offered: "6s", turn: 8, doraIndicator: "北", rivers: { toimen: ["7p", "8s"], shimocha: ["7p", "8s"] },
    context: "リーチなし。河は関連牌のみ抜粋。7筒と8索はそれぞれ手牌に2枚、河に2枚見えています。赤牌・本場・供託なし。",
    options: [chi(["4s", "5s"], "9m", "形の上ではタンヤオのテンパイです。", "7筒・8索は各4枚見えており、そのままではアガリ牌が残りません。", "役はありますが、現在の待ちで新たにアガれる牌はありません。")],
    pass: pass("別の形へ変化する手牌とリーチの余地を残します。", "今すぐの形式テンパイは取りません。", "待ちを組み直してアガれる形を目指します。"), recommendedAction: "pass",
    explanation: "チー後は7筒・8索待ちですが、どちらも4枚全て見えています。8巡目で形式テンパイを急ぐ条件ではないので、今はスルーして形を変える方を推奨します。", checkpoint: "待ちの種類だけでなく、残り枚数を数えます。" }),
  question({ id: "a-furiten", difficulty: "advanced", category: "shape", title: "自分の河も待ちと照合する", hand: "2349m45677p4588s", offered: "6s", turn: 4, rivers: { self: ["7p"] }, confidence: "medium",
    context: "4巡目、リーチなし。自分はすでに7筒を切っています。河は該当牌だけを抜粋。赤牌・本場・供託なし。",
    options: [chi(["4s", "5s"], "9m", "タンヤオのテンパイには進み、ツモならアガれます。", "7筒を自分で切っているため、8索を含めてロンできないフリテンです。", "タンヤオがありますが、フリテンのため現在の待ちはツモ限定です。")],
    pass: pass("序盤に待ちを組み直し、門前の価値を残せます。", "今すぐツモ専用テンパイを取ることは見送ります。", "新しい待ちでのリーチなどを狙います。"), recommendedAction: "pass",
    explanation: "チーは合法ですが、7筒・8索待ちのうち7筒を自分で切っています。フリテンは片方だけでなく待ち全体のロンを止めるため、序盤はスルーして形を組み直す方を推奨します。", checkpoint: "フリテンでも鳴くことやツモアガリ自体は禁止されません。" }),
  question({ id: "a-dealer-speed", difficulty: "advanced", category: "speed", title: "親の終盤テンパイ", hand: "456m34588p45s白白中", offered: "白", offeredBy: "toimen", seatWind: "東", turn: 12, scores: [21000, 29000, 27000, 23000], confidence: "medium",
    options: [pon("白", "中", "親の両面テンパイになり、アガリや連荘を目指せます。", "安い役牌手なので、リーチを受けた後は押し引きをやり直します。", "白1翻。親なので子よりアガリ点が高くなります。")],
    pass: pass("親リーチの打点を残せます。", "12巡目に一向聴のまま残りの手番を待ちます。", "親の門前リーチを狙うには、先にテンパイが必要です。"), recommendedAction: "pon",
    explanation: "親で12巡目、他家リーチはありません。白をポンすれば両面テンパイを取り、連荘にもつながります。親だから無条件に鳴くのではなく、この巡目と待ちを根拠にポン寄りとします。", checkpoint: "親の点数と連荘価値は、役と待ちの確認の後に加えます。" }),
  question({ id: "a-second-call-defense", difficulty: "advanced", category: "defense", title: "二副露にする前に守備を見る", hand: "234m5688p45s東", melds: [{ kind: "pon", tiles: ["白", "白", "白"] }], offered: "7p", seatWind: "西", roundWind: "南", roundNumber: 3, turn: 9, scores: [23000, 21000, 36000, 19000], riichiBy: "toimen", riichiSticks: 1, rivers: { toimen: ["9m", "2m", "9s", "5s"] }, confidence: "medium",
    context: "自分は西家のトップ。対面の東家がリーチ。河は抜粋。赤牌・本場なし、供託1本。",
    options: [chi(["5p", "6p"], "東", "白の役で両面テンパイを取れます。", "東は現物でなく、親リーチに対して安い手で押します。手牌も7枚になります。", "白1翻の仕掛け。打点条件上、今すぐ押す必要は小さい局面です。")],
    pass: pass("対面の現物2萬を保持し、点棒を守る選択を残します。", "白の両面テンパイの機会は逃します。", "すでに一副露なので、門前リーチを残すためのスルーではありません。"), recommendedAction: "pass",
    explanation: "二副露すれば両面テンパイですが、東を親リーチへ切る必要があります。トップの南3局では、現物2萬を残す守備寄りのスルーを推奨します。副露の数だけでなく直後の打牌が判断材料です。", checkpoint: "10枚から7枚になると、安全牌候補を選ぶ余地も変わります。" }),
  question({ id: "a-two-actions", difficulty: "advanced", category: "shape", title: "ポンもチーもできる形", hand: "2234m45677p45s東北", offered: "2m", turn: 3, confidence: "medium",
    options: [pon("2m", "北", "222萬を固定し、34萬のターツを残せます。", "東が残るため役はまだ未確定で、門前の柔軟性を失います。", "東を処理してタンヤオなどを作る必要があります。"), chi(["3m", "4m"], "北", "234萬を固定し、22萬を雀頭候補にできます。", "面子の使い直しとリーチがなくなり、東の処理も残ります。", "タンヤオは東を処理してから。ドラだけでは役になりません。")],
    pass: pass("2234萬を面子・対子・ターツとして使い直せます。", "2萬を鳴いて面子を固定する機会を見送ります。", "門前リーチを残し、東を雀頭にする選択もできます。"), recommendedAction: "pass",
    explanation: "2萬はポンもチーもできますが、3巡目でどちらも役がまだ確定しません。2234萬の使い直しとリーチを残すスルー寄りとします。比較するチーは234萬、ポンは222萬で、いずれも北を切った形です。", checkpoint: "同じ牌を鳴いても、ポンとチーで残るブロックが違います。" }),
  question({ id: "a-double-south", difficulty: "advanced", category: "value", title: "ダブ南とドラ2を速度に変える", hand: "456m34588p45s南南中", offered: "南", offeredBy: "shimocha", seatWind: "南", roundWind: "南", roundNumber: 3, turn: 8, doraIndicator: "7p", scores: [31000, 22000, 28000, 19000], confidence: "medium",
    options: [pon("南", "中", "ダブ南とドラ2枚を確保して両面テンパイになります。", "リーチは失い、切る中の安全も別に確認する必要があります。", "場風・自風の南で2翻、ドラ2で合計4翻。4翻でも符によって満貫未満です。")],
    pass: pass("リーチを加えて満貫以上を狙えます。", "十分な打点のある即テンパイを逃します。", "ダブ南・ドラ2・リーチなら5翻を狙えます。"), recommendedAction: "pon",
    explanation: "南場の南家なので、南は2翻の役牌です。ドラ8筒を2枚持ち、ポンしても4翻の両面テンパイになるため、今回は速度を優先するポン寄りです。4翻30符は7,700点で、常に満貫とは限らない点も確認しましょう。", checkpoint: "役の翻数、ドラの枚数、符を分けて数えます。" })
];

export const callRepresentativeIds = ["b-white-tenpai", "b-no-yaku", "m-white-early", "m-white-late", "a-defense"];
