export type HighlightClip = {
  id: string;
  tag: string;
  title: string;
  channel: string;
  url: string;
  isShort?: boolean;
  date?: string;
  competition?: string;
};

export const yakumanClips: readonly HighlightClip[] = [
  {
    id: "VNcXfxNfF3M",
    tag: "小四喜",
    title:
      "【Mリーグ】史上初！！役満小四喜！！KADOKAWAサクラナイツ『堀 慎吾』全国の人々が見ている！？最後尾からの逆転あるか！？【麻雀/名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=VNcXfxNfF3M",
  },
  {
    id: "2TtRuHvgnSg",
    tag: "四暗刻",
    title:
      "【2025-26】個人役満和了数最多！ #滝沢和典 ファイナル進出を決定づける親の四暗刻【#Mリーグ 公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=2TtRuHvgnSg",
  },
  {
    id: "xFwdABCKhWI",
    tag: "四暗刻",
    title:
      "【Mリーグ/麻雀】解説/金「これは神の麻雀見たわ…」赤坂ドリブンズ『鈴木 たろう』テンパイ外しからの四暗刻を和了！！【名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=xFwdABCKhWI",
  },
  {
    id: "2WnA9YydO1g",
    tag: "四暗刻",
    title: "【天からの贈り物】Mリーグ　高宮まりが初の役満を達成‼奇跡の瞬間を見逃すな",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/watch?v=2WnA9YydO1g",
  },
  {
    id: "iZ5oCzTdL6Y",
    tag: "役満集",
    title: "【Mリーグ】ダイジェストで振り返る、2023シーズンの役満集！",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/watch?v=iZ5oCzTdL6Y",
  },
  {
    id: "KBhCqYKsPT8",
    tag: "小四喜",
    title:
      "【未公開あり】堀慎吾 Mリーグ初『小四喜』成就の瞬間の楽屋の様子と感想戦【サクラナイツ公式】",
    channel: "KADOKAWAサクラナイツ公式チャンネル",
    url: "https://www.youtube.com/watch?v=KBhCqYKsPT8",
  },
  {
    id: "GMZIHTB9Au4",
    tag: "大三元",
    title:
      "【2025-26】鬼神 #下石戟 の手に舞い降りた三種の神器！開局に閃光の親大三元！【#Mリーグ 公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=GMZIHTB9Au4",
  },
  {
    id: "UXbfKTRMMKY",
    tag: "四暗刻単騎",
    title: "黒沢咲、大逆転の四暗刻単騎【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=UXbfKTRMMKY",
  },
  {
    id: "oVoMFMOhRLk",
    tag: "大三元",
    title: "近藤誠一、Mリーグ2019初役満の大三元【Mリーグ公式役満集#1】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=oVoMFMOhRLk",
  },
  {
    id: "fxQtTolXgfU",
    tag: "国士無双",
    title: "佐々木寿人、Mリーグ史上初の役満・国士無双【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=fxQtTolXgfU",
  },
  {
    id: "z9tbXxF_YCw",
    tag: "国士無双",
    title: "魚谷侑未、東1局いきなりの国士無双！【Mリーグ公式役満集#6】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=z9tbXxF_YCw",
  },
  {
    id: "hLC80pstk7o",
    tag: "大三元",
    title: "朝倉康心、ファイナルで親の大三元！本人コメント付き【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=hLC80pstk7o",
  },
  {
    id: "1h3vJ_vx_JY",
    tag: "国士無双",
    title: "【2024-25】レギュラー最終戦に大波乱を起こす園田賢の国士無双！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=1h3vJ_vx_JY",
  },
  {
    id: "PDl0C8JMHHg",
    tag: "四暗刻",
    title: "伊達朱里紗、開幕初日に役満・四暗刻を和了【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=PDl0C8JMHHg",
  },
  {
    id: "vqXvgrSHjr8",
    tag: "四暗刻",
    title: "【2024-25】二階堂瑠美、親の四暗刻ツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=vqXvgrSHjr8",
  },
  {
    id: "I3Sv-WxHjk4",
    tag: "四暗刻",
    title: "【2025-26】2枚目もスルー！浅井堂岐、気合いの四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=I3Sv-WxHjk4",
  },
  {
    id: "HxkbCvUJB6E",
    tag: "四暗刻",
    title: "【2025-26】幻の三色同刻！？白鳥翔、伝説に残る四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=HxkbCvUJB6E",
  },
  {
    id: "W2jraWXAukY",
    tag: "大三元",
    title: "【役満炸裂】大三元！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=W2jraWXAukY",
    date: "2019年2月7日",
    competition: "Mリーグ本戦・滝沢和典",
  },
  {
    id: "rm2KrdrK3FU",
    tag: "大三元",
    title: "前原雄大、親番で役満・大三元を炸裂！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=rm2KrdrK3FU",
    date: "2019年3月10日",
    competition: "Mリーグ本戦・前原雄大",
  },
  {
    id: "9fYhjDfdNQ0",
    tag: "四暗刻",
    title: "瀬戸熊直樹、Mリーグ初の四暗刻成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=9fYhjDfdNQ0",
    date: "2019年10月26日",
    competition: "Mリーグ本戦・瀬戸熊直樹",
  },
  {
    id: "RAd7IbvQVKM",
    tag: "四暗刻",
    title: "沢崎誠、鮮やかな四暗刻成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=RAd7IbvQVKM",
    date: "2019年11月14日",
    competition: "Mリーグ本戦・沢崎誠",
  },
  {
    id: "eZ9bdpIp6hM",
    tag: "四暗刻単騎",
    title: "白鳥翔、四暗刻単騎待ち【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=eZ9bdpIp6hM",
    date: "2019年12月12日",
    competition: "Mリーグ本戦・白鳥翔",
  },
  {
    id: "Y5U5hKxSmSA",
    tag: "四暗刻",
    title: "魚谷侑未、四暗刻をツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=Y5U5hKxSmSA",
    date: "2020年3月3日",
    competition: "Mリーグ本戦・魚谷侑未",
  },
  {
    id: "8IYr3FHyxZU",
    tag: "四暗刻",
    title: "松本吉弘、最速で四暗刻和了【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=8IYr3FHyxZU",
    date: "2020年11月16日",
    competition: "Mリーグ本戦・松本吉弘",
  },
  {
    id: "OFqWQLeTvR4",
    tag: "四暗刻",
    title: "堀慎吾、嶺上開花からの四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=OFqWQLeTvR4",
    date: "2021年1月2日",
    competition: "Mリーグ本戦・堀慎吾",
  },
  {
    id: "S-JENyeKLZ8",
    tag: "四暗刻",
    title: "松本吉弘、リーチ一発ツモ四暗刻！【Mリーグ名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=S-JENyeKLZ8",
    date: "2021年4月29日",
    competition: "Mリーグ本戦・松本吉弘",
  },
  {
    id: "94-FlWHQ0rQ",
    tag: "親の四暗刻",
    title: "佐々木寿人、セミファイナルで親の四暗刻！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=94-FlWHQ0rQ",
    date: "2022年3月22日",
    competition: "Mリーグ本戦・佐々木寿人",
  },
  {
    id: "NnCtLPnDVkA",
    tag: "四暗刻単騎",
    title: "二階堂亜樹、狙いすました四暗刻単騎リーチ【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=NnCtLPnDVkA",
    date: "2023年2月14日",
    competition: "Mリーグ本戦・二階堂亜樹",
  },
  {
    id: "-GxK80NY3o0",
    tag: "国士無双",
    title: "園田賢、オーラスに国士無双炸裂！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=-GxK80NY3o0",
    date: "2023年2月23日",
    competition: "Mリーグ本戦・園田賢",
  },
  {
    id: "YPdYrUVO7j8",
    tag: "親の四暗刻",
    title: "滝沢和典、クール過ぎる親の四暗刻ツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=YPdYrUVO7j8",
    date: "2023年5月16日",
    competition: "Mリーグ本戦・滝沢和典",
  },
  {
    id: "jNQnHNC3xas",
    tag: "大三元",
    title: "鈴木大介、チームの窮地を救う大三元成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=jNQnHNC3xas",
    date: "2025年1月13日",
    competition: "Mリーグ本戦・鈴木大介",
  },
  {
    id: "aNaQUBFzweg",
    tag: "国士無双",
    title: "勝又健志、チームの窮地を救った国士無双【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=aNaQUBFzweg",
    date: "2025年3月13日",
    competition: "Mリーグ本戦・勝又健志",
  },
  {
    id: "iHFVTGjj5uo",
    tag: "四暗刻",
    title: "仲林圭、2025-26シーズン開幕戦で四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=iHFVTGjj5uo",
    date: "2025年9月15日",
    competition: "Mリーグ本戦・仲林圭",
  },
  {
    id: "fM8VwdwVLMk",
    tag: "国士無双13面待ち",
    title: "岡田紗佳、国士無双13面待ち！【麻雀最強戦2022】",
    channel: "麻雀最強戦チャンネルpresented竹書房",
    url: "https://www.youtube.com/watch?v=fM8VwdwVLMk",
    competition: "麻雀最強戦2022 Mリーグスペシャルマッチ・岡田紗佳",
  },
  {
    id: "nCwcxTuMAJY",
    tag: "四暗刻",
    title: "村上淳、四暗刻炸裂！日清食品 presents 麺飯位決定戦",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=nCwcxTuMAJY",
    competition: "日清食品 presents 麺飯位決定戦・村上淳",
  },
  {
    id: "o8iU3-6Uebg",
    tag: "大三元",
    title: "園田賢、初戦ラスから起死回生の大三元！【Mトーナメント】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=o8iU3-6Uebg",
    competition: "Mトーナメント2023・園田賢",
  },
  {
    id: "OvjaPcfaHMI",
    tag: "四暗刻単騎",
    title: "黒沢咲、伝説再び！四暗刻単騎【Mトーナメント】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=OvjaPcfaHMI",
    competition: "Mトーナメント2025・黒沢咲",
  },
] as const;

export const memorableClips: readonly HighlightClip[] = [
  {
    id: "RYh81ICq4VQ",
    tag: "10万点超",
    title: "【伊達ちゃん無双】伊達朱里紗Mリーグ史上初の10万点超トップ#shorts",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/shorts/RYh81ICq4VQ",
    isShort: true,
  },
  {
    id: "RkYZlAWVll0",
    tag: "名勝負",
    title:
      "【Mリーグ/麻雀】恐ろしい… 何だコノ配牌は…？！KONAMI 麻雀格闘倶楽部「滝沢 和典」２着目のオーラス！！追いかける多井！！チャンスをモノにできるか？！【名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=RkYZlAWVll0",
  },
  {
    id: "gQWXAOqXd5M",
    tag: "ビタ止め",
    title:
      "【Mリーグ】ビタ止めに次ぐビタ止め！！『伊達朱里紗』vs『二階堂瑠美』vs『近藤誠一』vs『 堀慎吾』マンガで描いたら笑われる！？全員テンパイからまさかの結末！！【麻雀/名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=gQWXAOqXd5M",
  },
  {
    id: "V5ay0eETSgM",
    tag: "名勝負",
    title: "【Mリーグ】これが雷電、これが黒沢咲さん【切り抜き】",
    channel: "【Mリーグ切り抜き】ヨシノノ人間麻雀人間。",
    url: "https://www.youtube.com/watch?v=V5ay0eETSgM",
  },
  {
    id: "S2MHTglmAqg",
    tag: "奇跡の倍満",
    title: "【伝説の試合】近藤誠一、条件を満たす一発ツモ・裏ドラのドラマティック倍満",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=S2MHTglmAqg",
  },
] as const;
