export type HighlightClip = {
  id: string;
  tag: string;
  title: string;
  summary?: string;
  channel: string;
  url: string;
  isShort?: boolean;
  date?: string;
  competition?: string;
};

const clipEditorialNotes: Readonly<Record<string, string>> = {
  VNcXfxNfF3M: "終盤の逆転条件が絡む中、堀慎吾が小四喜を完成させるまでの緊張感に注目です。",
  "2TtRuHvgnSg": "ファイナル進出を大きく引き寄せた、滝沢和典の親四暗刻を試合の流れとともに振り返れます。",
  xFwdABCKhWI: "テンパイを一度外した鈴木たろうが四暗刻へたどり着く、構想と決断が際立つ一局です。",
  "2WnA9YydO1g": "高宮まりが自身初の役満を成就する瞬間を、卓上の空気の変化とともに楽しめます。",
  iZ5oCzTdL6Y: "2023シーズンに生まれた複数の役満を続けて見比べられるダイジェストです。",
  KBhCqYKsPT8: "堀慎吾の小四喜を対局映像だけでなく、楽屋の反応と感想戦からも味わえる一本です。",
  GMZIHTB9Au4: "開局直後から下石戟が親の大三元を仕上げる、速度と破壊力が際立つ場面です。",
  UXbfKTRMMKY: "黒沢咲が四暗刻単騎で大逆転を決めるまでの、静かな手組みと劇的な結末が見どころです。",
  oVoMFMOhRLk: "近藤誠一がMリーグ2019最初の役満を大三元で決めた、シーズンを象徴する一局です。",
  fxQtTolXgfU: "Mリーグ史上初の役満となった佐々木寿人の国士無双。その歴史的瞬間を確認できます。",
  z9tbXxF_YCw: "東1局から魚谷侑未が国士無双を成就し、試合の空気を一変させる場面です。",
  hLC80pstk7o: "大舞台のファイナルで朝倉康心が親の大三元を決める重圧と、本人の振り返りが見どころです。",
  "1h3vJ_vx_JY": "レギュラー最終戦で園田賢が国士無双を完成させる、順位争いの緊張感に満ちた一局です。",
  PDl0C8JMHHg: "開幕初日に伊達朱里紗が四暗刻を和了する、シーズン序盤から生まれた衝撃の場面です。",
  vqXvgrSHjr8: "二階堂瑠美が親番で四暗刻をツモり、一撃で大きく局面を動かす迫力を味わえます。",
  "I3Sv-WxHjk4": "浅井堂岐が鳴ける牌を見送り、四暗刻への道を選び切った判断に注目したい一局です。",
  HxkbCvUJB6E: "三色同刻も見える珍しい手牌から、白鳥翔が四暗刻を完成させる変化の多い一局です。",
  W2jraWXAukY: "滝沢和典が大三元を決めた初期Mリーグの役満。三元牌がそろう過程を楽しめます。",
  rm2KrdrK3FU: "前原雄大が親番で大三元を炸裂させる、打点の大きさと場の緊迫感が伝わる一局です。",
  "9fYhjDfdNQ0": "瀬戸熊直樹がMリーグで初めて四暗刻を成就した、記録にも残る場面です。",
  RAd7IbvQVKM: "沢崎誠らしい落ち着いた進行から四暗刻を仕上げる、手牌育成の妙が光る一局です。",
  eZ9bdpIp6hM: "白鳥翔が通常の四暗刻より難しい単騎待ちを選び、役満を狙い切る勝負手です。",
  Y5U5hKxSmSA: "魚谷侑未が四暗刻をツモるまでの手牌の伸びと、和了の瞬間の熱気を振り返れます。",
  "8IYr3FHyxZU": "松本吉弘がスピード感のある進行で四暗刻を完成させる、鮮烈な役満シーンです。",
  OFqWQLeTvR4: "嶺上開花が絡む展開から堀慎吾が四暗刻へ到達する、偶然と構想が重なる一局です。",
  "S-JENyeKLZ8": "松本吉弘がリーチ一発ツモで四暗刻を決める、結末まで目が離せない劇的な場面です。",
  "94-FlWHQ0rQ": "セミファイナルで佐々木寿人が親の四暗刻を決め、勝負を大きく動かした一局です。",
  NnCtLPnDVkA: "二階堂亜樹が四暗刻単騎をリーチして押し切る、覚悟の選択が際立つ場面です。",
  "-GxK80NY3o0": "オーラスで園田賢が国士無双を成就。最後まで逆転を追う条件戦の醍醐味があります。",
  YPdYrUVO7j8: "滝沢和典が親の四暗刻をツモっても表情を崩さない、打牌と所作まで印象的な一局です。",
  jNQnHNC3xas: "チームが苦しい状況で鈴木大介が大三元を成就する、勝負強さが表れた場面です。",
  aNaQUBFzweg: "勝又健志が国士無双でチームの窮地を救う、局面と結果の重みが伝わる一局です。",
  iHFVTGjj5uo: "シーズン開幕戦で仲林圭が四暗刻を完成させる、スタートから衝撃的な一局です。",
  fM8VwdwVLMk: "岡田紗佳が国士無双13面待ちを完成させる、待ちの広さと希少性が際立つ場面です。",
  nCwcxTuMAJY: "特別対局で村上淳が四暗刻を決める、普段のリーグ戦とは違う空気も楽しめます。",
  "o8iU3-6Uebg": "初戦ラスの状況から園田賢が大三元で流れを変える、トーナメントならではの一撃です。",
  OvjaPcfaHMI: "黒沢咲が再び四暗刻単騎を成就。大物手を育て切る打ち筋に注目です。",
  RYh81ICq4VQ: "伊達朱里紗が10万点を超えるトップを記録した、得点の伸び方まで圧巻の短編です。",
  RkYZlAWVll0: "オーラスの好配牌を受けた滝沢和典と追う多井隆晴。着順争いの駆け引きが見どころです。",
  gQWXAOqXd5M: "全員テンパイの緊迫した局面で放銃を回避し続ける、守備判断を楽しめる一局です。",
  V5ay0eETSgM: "黒沢咲の打ち筋とTEAM雷電らしい物語性が凝縮された、ファンに長く語られる場面です。",
  S2MHTglmAqg: "近藤誠一が一発ツモと裏ドラの条件を満たして倍満へ届く、逆転条件の妙が詰まった一局です。",
  B7AeodujvK0: "丸山奏子がロンを見逃し、最終ツモの倍満で4着から逆転。デビュー戦の決断が光ります。",
  gLavgu41_pk: "内川幸太郎が危険牌を止めてから三倍満をツモる、守備と攻撃が連続する名場面です。",
  KlKddK1mCvk: "トップまで大差のオーラスで白鳥翔が清一色ドラ6を仕上げる、漫画のような逆転劇です。",
  "4R7FLjnTck0": "普段は打牌の速い佐々木寿人が128秒考え抜く、選択の重さを追体験できる場面です。",
  wSP6ylhDnj4: "瑞原明奈が高め三色ツモという厳しい条件を満たす、オーラスの点数計算も面白い一局です。",
  czf5jbD4yVA: "魚谷侑未が2軒リーチを制し、高めツモと裏ドラで逆転する終盤戦の名場面です。",
  XIglNVrxU_4: "佐々木寿人が13翻の親三倍満を決める、役満ではない最高峰の打点を味わえます。",
  H2BePFxGijk: "多井隆晴が他家の攻勢を読み切って危険牌を止める、守備技術に焦点を当てた一局です。",
  "6TfEHQZxfZQ": "村上淳がオーラスの満貫ツモで逆転し、チームの4連勝をつないだ物語性のある一局です。",
  "fTBYL7lwa-I": "鈴木たろうがリーチをかけず満貫直撃を選ぶ、局面判断の巧さが分かる逆転劇です。",
  IjiG7TgzMnA: "満貫を放銃した直後、萩原聖人が三色同順の跳満で取り返す展開の速さが魅力です。",
};

function addEditorialNotes(clips: readonly HighlightClip[]): readonly HighlightClip[] {
  return clips.map((clip) => ({
    ...clip,
    summary: clip.summary ?? clipEditorialNotes[clip.id],
  }));
}

const yakumanClipCatalog: readonly HighlightClip[] = [
  {
    id: "VNcXfxNfF3M",
    tag: "小四喜",
    title:
      "【Mリーグ】史上初！！役満小四喜！！KADOKAWAサクラナイツ『堀 慎吾』全国の人々が見ている！？最後尾からの逆転あるか！？【麻雀/名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=VNcXfxNfF3M",
  },
  {
    id: "2TtRuHvgnSg",
    tag: "四暗刻",
    title:
      "【2025-26】個人役満和了数最多！ #滝沢和典 ファイナル進出を決定づける親の四暗刻【#Mリーグ 公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=2TtRuHvgnSg",
  },
  {
    id: "xFwdABCKhWI",
    tag: "四暗刻",
    title:
      "【Mリーグ/麻雀】解説/金「これは神の麻雀見たわ…」赤坂ドリブンズ『鈴木 たろう』テンパイ外しからの四暗刻を和了！！【名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=xFwdABCKhWI",
  },
  {
    id: "2WnA9YydO1g",
    tag: "四暗刻",
    title: "【天からの贈り物】Mリーグ　高宮まりが初の役満を達成‼奇跡の瞬間を見逃すな",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/watch?v=2WnA9YydO1g",
  },
  {
    id: "iZ5oCzTdL6Y",
    tag: "役満集",
    title: "【Mリーグ】ダイジェストで振り返る、2023シーズンの役満集！",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/watch?v=iZ5oCzTdL6Y",
  },
  {
    id: "KBhCqYKsPT8",
    tag: "小四喜",
    title:
      "【未公開あり】堀慎吾 Mリーグ初『小四喜』成就の瞬間の楽屋の様子と感想戦【サクラナイツ公式】",
    channel: "KADOKAWAサクラナイツ公式チャンネル",
    url: "https://www.youtube.com/watch?v=KBhCqYKsPT8",
  },
  {
    id: "GMZIHTB9Au4",
    tag: "大三元",
    title:
      "【2025-26】鬼神 #下石戟 の手に舞い降りた三種の神器！開局に閃光の親大三元！【#Mリーグ 公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=GMZIHTB9Au4",
  },
  {
    id: "UXbfKTRMMKY",
    tag: "四暗刻単騎",
    title: "黒沢咲、大逆転の四暗刻単騎【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=UXbfKTRMMKY",
  },
  {
    id: "oVoMFMOhRLk",
    tag: "大三元",
    title: "近藤誠一、Mリーグ2019初役満の大三元【Mリーグ公式役満集#1】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=oVoMFMOhRLk",
  },
  {
    id: "fxQtTolXgfU",
    tag: "国士無双",
    title: "佐々木寿人、Mリーグ史上初の役満・国士無双【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=fxQtTolXgfU",
  },
  {
    id: "z9tbXxF_YCw",
    tag: "国士無双",
    title: "魚谷侑未、東1局いきなりの国士無双！【Mリーグ公式役満集#6】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=z9tbXxF_YCw",
  },
  {
    id: "hLC80pstk7o",
    tag: "大三元",
    title: "朝倉康心、ファイナルで親の大三元！本人コメント付き【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=hLC80pstk7o",
  },
  {
    id: "1h3vJ_vx_JY",
    tag: "国士無双",
    title: "【2024-25】レギュラー最終戦に大波乱を起こす園田賢の国士無双！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=1h3vJ_vx_JY",
  },
  {
    id: "PDl0C8JMHHg",
    tag: "四暗刻",
    title: "伊達朱里紗、開幕初日に役満・四暗刻を和了【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=PDl0C8JMHHg",
  },
  {
    id: "vqXvgrSHjr8",
    tag: "四暗刻",
    title: "【2024-25】二階堂瑠美、親の四暗刻ツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=vqXvgrSHjr8",
  },
  {
    id: "I3Sv-WxHjk4",
    tag: "四暗刻",
    title: "【2025-26】2枚目もスルー！浅井堂岐、気合いの四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=I3Sv-WxHjk4",
  },
  {
    id: "HxkbCvUJB6E",
    tag: "四暗刻",
    title: "【2025-26】幻の三色同刻！？白鳥翔、伝説に残る四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=HxkbCvUJB6E",
  },
  {
    id: "W2jraWXAukY",
    tag: "大三元",
    title: "【役満炸裂】大三元！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=W2jraWXAukY",
    date: "2019年2月7日",
    competition: "Mリーグ本戦・滝沢和典",
  },
  {
    id: "rm2KrdrK3FU",
    tag: "大三元",
    title: "前原雄大、親番で役満・大三元を炸裂！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=rm2KrdrK3FU",
    date: "2019年3月10日",
    competition: "Mリーグ本戦・前原雄大",
  },
  {
    id: "9fYhjDfdNQ0",
    tag: "四暗刻",
    title: "瀬戸熊直樹、Mリーグ初の四暗刻成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=9fYhjDfdNQ0",
    date: "2019年10月26日",
    competition: "Mリーグ本戦・瀬戸熊直樹",
  },
  {
    id: "RAd7IbvQVKM",
    tag: "四暗刻",
    title: "沢崎誠、鮮やかな四暗刻成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=RAd7IbvQVKM",
    date: "2019年11月14日",
    competition: "Mリーグ本戦・沢崎誠",
  },
  {
    id: "eZ9bdpIp6hM",
    tag: "四暗刻単騎",
    title: "白鳥翔、四暗刻単騎待ち【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=eZ9bdpIp6hM",
    date: "2019年12月12日",
    competition: "Mリーグ本戦・白鳥翔",
  },
  {
    id: "Y5U5hKxSmSA",
    tag: "四暗刻",
    title: "魚谷侑未、四暗刻をツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=Y5U5hKxSmSA",
    date: "2020年3月3日",
    competition: "Mリーグ本戦・魚谷侑未",
  },
  {
    id: "8IYr3FHyxZU",
    tag: "四暗刻",
    title: "松本吉弘、最速で四暗刻和了【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=8IYr3FHyxZU",
    date: "2020年11月16日",
    competition: "Mリーグ本戦・松本吉弘",
  },
  {
    id: "OFqWQLeTvR4",
    tag: "四暗刻",
    title: "堀慎吾、嶺上開花からの四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=OFqWQLeTvR4",
    date: "2021年1月2日",
    competition: "Mリーグ本戦・堀慎吾",
  },
  {
    id: "S-JENyeKLZ8",
    tag: "四暗刻",
    title: "松本吉弘、リーチ一発ツモ四暗刻！【Mリーグ名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=S-JENyeKLZ8",
    date: "2021年4月29日",
    competition: "Mリーグ本戦・松本吉弘",
  },
  {
    id: "94-FlWHQ0rQ",
    tag: "親の四暗刻",
    title: "佐々木寿人、セミファイナルで親の四暗刻！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=94-FlWHQ0rQ",
    date: "2022年3月22日",
    competition: "Mリーグ本戦・佐々木寿人",
  },
  {
    id: "NnCtLPnDVkA",
    tag: "四暗刻単騎",
    title: "二階堂亜樹、狙いすました四暗刻単騎リーチ【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=NnCtLPnDVkA",
    date: "2023年2月14日",
    competition: "Mリーグ本戦・二階堂亜樹",
  },
  {
    id: "-GxK80NY3o0",
    tag: "国士無双",
    title: "園田賢、オーラスに国士無双炸裂！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=-GxK80NY3o0",
    date: "2023年2月23日",
    competition: "Mリーグ本戦・園田賢",
  },
  {
    id: "YPdYrUVO7j8",
    tag: "親の四暗刻",
    title: "滝沢和典、クール過ぎる親の四暗刻ツモ！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=YPdYrUVO7j8",
    date: "2023年5月16日",
    competition: "Mリーグ本戦・滝沢和典",
  },
  {
    id: "jNQnHNC3xas",
    tag: "大三元",
    title: "鈴木大介、チームの窮地を救う大三元成就！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=jNQnHNC3xas",
    date: "2025年1月13日",
    competition: "Mリーグ本戦・鈴木大介",
  },
  {
    id: "aNaQUBFzweg",
    tag: "国士無双",
    title: "勝又健志、チームの窮地を救った国士無双【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=aNaQUBFzweg",
    date: "2025年3月13日",
    competition: "Mリーグ本戦・勝又健志",
  },
  {
    id: "iHFVTGjj5uo",
    tag: "四暗刻",
    title: "仲林圭、2025-26シーズン開幕戦で四暗刻【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=iHFVTGjj5uo",
    date: "2025年9月15日",
    competition: "Mリーグ本戦・仲林圭",
  },
  {
    id: "fM8VwdwVLMk",
    tag: "国士無双13面待ち",
    title: "岡田紗佳、国士無双13面待ち！【麻雀最強戦2022】",
    channel: "麻雀最強戦チャンネルpresented竹書房",
    url: "https://www.youtube.com/watch?v=fM8VwdwVLMk",
    competition: "麻雀最強戦2022 Mリーグスペシャルマッチ・岡田紗佳",
  },
  {
    id: "nCwcxTuMAJY",
    tag: "四暗刻",
    title: "村上淳、四暗刻炸裂！日清食品 presents 麺飯位決定戦",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=nCwcxTuMAJY",
    competition: "日清食品 presents 麺飯位決定戦・村上淳",
  },
  {
    id: "o8iU3-6Uebg",
    tag: "大三元",
    title: "園田賢、初戦ラスから起死回生の大三元！【Mトーナメント】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=o8iU3-6Uebg",
    competition: "Mトーナメント2023・園田賢",
  },
  {
    id: "OvjaPcfaHMI",
    tag: "四暗刻単騎",
    title: "黒沢咲、伝説再び！四暗刻単騎【Mトーナメント】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=OvjaPcfaHMI",
    competition: "Mトーナメント2025・黒沢咲",
  },
] as const;

const memorableClipCatalog: readonly HighlightClip[] = [
  {
    id: "RYh81ICq4VQ",
    tag: "10万点超",
    title: "【伊達ちゃん無双】伊達朱里紗Mリーグ史上初の10万点超トップ#shorts",
    channel: "Mリーグの名場面集【切り抜き】",
    url: "https://www.youtube.com/shorts/RYh81ICq4VQ",
    isShort: true,
  },
  {
    id: "RkYZlAWVll0",
    tag: "名勝負",
    title:
      "【Mリーグ/麻雀】恐ろしい… 何だコノ配牌は…？！KONAMI 麻雀格闘倶楽部「滝沢 和典」２着目のオーラス！！追いかける多井！！チャンスをモノにできるか？！【名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=RkYZlAWVll0",
  },
  {
    id: "gQWXAOqXd5M",
    tag: "ビタ止め",
    title:
      "【Mリーグ】ビタ止めに次ぐビタ止め！！『伊達朱里紗』vs『二階堂瑠美』vs『近藤誠一』vs『 堀慎吾』マンガで描いたら笑われる！？全員テンパイからまさかの結末！！【麻雀/名場面】",
    channel: "Mリーグ 至極の一局 【名場面切り抜き】",
    url: "https://www.youtube.com/watch?v=gQWXAOqXd5M",
  },
  {
    id: "V5ay0eETSgM",
    tag: "名勝負",
    title: "【Mリーグ】これが雷電、これが黒沢咲さん【切り抜き】",
    channel: "【Mリーグ切り抜き】ヨシノノ人間麻雀人間。",
    url: "https://www.youtube.com/watch?v=V5ay0eETSgM",
  },
  {
    id: "S2MHTglmAqg",
    tag: "奇跡の倍満",
    title: "【伝説の試合】近藤誠一、条件を満たす一発ツモ・裏ドラのドラマティック倍満",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=S2MHTglmAqg",
  },
  {
    id: "B7AeodujvK0",
    tag: "伝説のデビュー戦",
    title: "丸山奏子、ロンを見逃して最終ツモで大逆転倍満！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=B7AeodujvK0",
    date: "2019年10月29日",
    competition: "Mリーグ本戦・丸山奏子",
  },
  {
    id: "gLavgu41_pk",
    tag: "神回避",
    title: "内川幸太郎、放銃牌を神回避からの追っかけリーチ・三倍満ツモ！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=gLavgu41_pk",
    competition: "Mリーグ本戦・内川幸太郎",
  },
  {
    id: "KlKddK1mCvk",
    tag: "奇跡の三倍満",
    title: "白鳥翔、清一色ドラ6でオーラス4着から大逆転三倍満！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=KlKddK1mCvk",
    date: "2020年2月13日",
    competition: "Mリーグ本戦・白鳥翔",
  },
  {
    id: "4R7FLjnTck0",
    tag: "128秒の大長考",
    title: "佐々木寿人、天国か地獄か…128秒の大長考の末に出した答えは？",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=4R7FLjnTck0",
    competition: "Mリーグ本戦・佐々木寿人",
  },
  {
    id: "wSP6ylhDnj4",
    tag: "執念の跳満",
    title: "瑞原明奈、高め三色のツモ条件をクリアした劇的なオーラス跳満！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=wSP6ylhDnj4",
    date: "2020年11月17日",
    competition: "Mリーグ本戦・瑞原明奈",
  },
  {
    id: "czf5jbD4yVA",
    tag: "オーラス大逆転",
    title: "魚谷侑未、2軒リーチを制して跳満ツモ・大逆転の2連勝！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=czf5jbD4yVA",
    date: "2019年10月24日",
    competition: "Mリーグ本戦・魚谷侑未",
  },
  {
    id: "XIglNVrxU_4",
    tag: "13翻・親三倍満",
    title: "佐々木寿人、13翻の親三倍満・12000オール！【Mリーグ公式】",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=XIglNVrxU_4",
    competition: "Mリーグ本戦・佐々木寿人",
  },
  {
    id: "H2BePFxGijk",
    tag: "神ビタ止め",
    title: "多井隆晴、全員が踏み込む中で解説も絶句する神ビタ止め！",
    channel: "M.LEAGUE 【切り抜きチャンネル】",
    url: "https://www.youtube.com/watch?v=H2BePFxGijk",
    competition: "Mリーグ本戦・多井隆晴",
  },
  {
    id: "6TfEHQZxfZQ",
    tag: "チーム4連勝",
    title: "村上淳、万感の満貫ツモで逆転してドリブンズ4連勝！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=6TfEHQZxfZQ",
    date: "2020年1月27日",
    competition: "Mリーグ本戦・村上淳",
  },
  {
    id: "fTBYL7lwa-I",
    tag: "勝負のダマテン",
    title: "鈴木たろう、勝負のダマテンから満貫直撃で逆転トップ！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=fTBYL7lwa-I",
    date: "2019年11月10日",
    competition: "Mリーグ本戦・鈴木たろう",
  },
  {
    id: "IjiG7TgzMnA",
    tag: "倍返しの跳満",
    title: "萩原聖人、満貫放銃の直後に三色同順の跳満で即リベンジ！",
    channel: "M.LEAGUE [プロ麻雀リーグ]",
    url: "https://www.youtube.com/watch?v=IjiG7TgzMnA",
    date: "2020年1月10日",
    competition: "Mリーグ本戦・萩原聖人",
  },
] as const;

export const yakumanClips = addEditorialNotes(yakumanClipCatalog);
export const memorableClips = addEditorialNotes(memorableClipCatalog);
