import type { RiichiQuestion } from "./riichiModel";

export const riichiHands = {
  ryanmen: "45m 234678p 45677s",
  kanchan: "35m 23445688p 789s",
  high: "45m 234678p 45666s",
  dealer: "456m 23678p 55789s",
  pinfu: "45m 123789p 45677s",
  pairs: "1144m 2277p 338s 北北",
  yakuhai: "23488m 678p 456s 白白",
  sanshoku: "24m 23488p 234678s",
  penchan: "789m 12p 12355s 123m",
  shanpon: "23488m 22678p 456s"
};

type RequiredQuestion = Pick<RiichiQuestion, "id" | "difficulty" | "category" | "title" | "hand" | "recommendedAction" | "explanation" | "checkpoint">;
const question = (data: RequiredQuestion & Partial<RiichiQuestion>): RiichiQuestion => ({ discard: "中", roundWind: "東", roundNumber: 2, seatWind: "南", turn: 7, wallTilesRemaining: 40, scores: [25000, 25000, 25000, 25000], doraIndicator: "白", riichiSticks: 0, confidence: "medium", context: "平場で打点も欲しい局面。他家のリーチ・副露はありません。宣言候補の牌は、現時点では危険と判断する情報がないものとします。", ...data });

// Original teaching positions. Scoring is calculated; recommendations are editorial, not EV estimates.
export const riichiQuestions: readonly RiichiQuestion[] = [
  question({ id: "b-ryanmen", difficulty: "beginner", category: "value", title: "良形で打点を上げる", hand: riichiHands.ryanmen, turn: 6, recommendedAction: "riichi",
    explanation: "3萬・6萬待ちで、ダマはタンヤオ・平和の2,000点。リーチで3,900点に上がります。まだ6巡目で大きな打点条件もないので、良形の攻撃手としてリーチ寄りです。", checkpoint: "待ちの広さと、リーチで増える点数をセットで見ます。" }),
  question({ id: "b-no-yaku", difficulty: "beginner", category: "yaku", title: "役なしテンパイはロンできない", hand: riichiHands.kanchan, turn: 9, recommendedAction: "riichi", confidence: "high",
    explanation: "4萬待ちの形ですが、ダマでは通常のロン役がありません。リーチなら役が付き、ロンできるようになります。ツモだけに頼らず、この巡目ではリーチを推奨します。", checkpoint: "ドラやテンパイという状態自体は、ロンの役になりません。" }),
  question({ id: "b-top-high", difficulty: "beginner", category: "conditions", title: "満貫のままトップを守る", hand: riichiHands.high, doraIndicator: "5s", roundWind: "南", roundNumber: 4, scores: [27000, 32000, 22000, 19000], targetRank: 1, turn: 10, recommendedAction: "dama",
    context: "オーラス・子のトップ。自分のアガリで終了し、トップを保つことを優先します。他家のリーチはありません。",
    explanation: "ダマでもタンヤオ・平和・ドラ3の満貫です。どこからアガってもトップを維持できます。打点を増やすより、ロン機会を残し、次の危険牌に対応できるダマ寄りとします。", checkpoint: "必要な打点がすでにあるなら、追加の翻以外の価値も見ます。" }),
  question({ id: "b-dealer", difficulty: "beginner", category: "value", title: "親の両面を攻撃手にする", hand: riichiHands.dealer, seatWind: "東", turn: 5, recommendedAction: "riichi",
    explanation: "1筒・4筒の両面待ちで、どちらにも平和があります。親の平場で、まだ5巡目。門前の1翻を加えて打点を上げるリーチを推奨します。", checkpoint: "親と子では同じ翻・符でも支払いが違います。" }),
  question({ id: "b-pairs", difficulty: "beginner", category: "value", title: "七対子にもリーチの1翻", hand: riichiHands.pairs, turn: 6, recommendedAction: "riichi",
    explanation: "8索単騎の七対子です。ダマのロン1,600点に対し、リーチなら3,200点。序盤の平場では打点を増やすリーチ寄りとします。単騎なので両面と同じアガリやすさとは考えません。", checkpoint: "七対子は25符。リーチの有無で点数を比べます。" }),
  question({ id: "b-late-lead", difficulty: "beginner", category: "defense", title: "終盤のリードは選択を残す", hand: riichiHands.pinfu, roundWind: "南", roundNumber: 3, turn: 16, wallTilesRemaining: 8, scores: [24000, 40000, 21000, 15000], recommendedAction: "dama",
    context: "南3局・子の大きなトップ。終盤で無理な失点を避けることを重視します。他家のリーチはありません。",
    explanation: "ダマでも平和でロンできます。残り巡目が少なく、今は大きなリードを守りたい場面です。点数を増やすために手を固定せず、次のツモで危険牌を引いたときの選択を残すダマ寄りです。", checkpoint: "ダマはベタオリではありません。テンパイと守備への移行を両立できます。" }),
  question({ id: "b-pinfu", difficulty: "beginner", category: "value", title: "平和のみの打点を増やす", hand: riichiHands.pinfu, turn: 5, recommendedAction: "riichi",
    explanation: "ダマでロンはできますが、平和のみの1,000点です。リーチなら2,000点。5巡目の両面で、特殊な点棒条件がないため、ここでは追加打点を優先します。", checkpoint: "『役があるから必ずダマ』ではなく、今の打点で十分かを考えます。" }),
  question({ id: "b-sanshoku-goal", difficulty: "beginner", category: "conditions", title: "カンチャンでも役が十分", hand: riichiHands.sanshoku, roundWind: "南", roundNumber: 4, turn: 10, scores: [27000, 32000, 22000, 19000], targetRank: 1, recommendedAction: "dama",
    context: "オーラス・子のトップ。自分のアガリで終了します。トップ維持を優先し、他家のリーチはありません。",
    explanation: "3萬を加えるとタンヤオ・三色同順の5,200点。ダマでもトップ維持に十分です。リーチで満貫になりますが、ここでは待ちを知らせず、守備の選択も残すダマを推奨します。", checkpoint: "待ちが悪いことと、ダマの役がないことは別です。" }),
  question({ id: "b-not-enough-points", difficulty: "beginner", category: "rules", title: "リーチ棒を出せる？", hand: riichiHands.ryanmen, scores: [35000, 900, 32100, 32000], recommendedAction: "dama", confidence: "high",
    context: "持ち点900点。今回は1,000点以上を必要とするルールで練習します。他家のリーチはありません。",
    explanation: "このルールではリーチ棒の1,000点を出せないため、リーチはできません。手牌の良さとは別に宣言条件を確認しましょう。ダマでもタンヤオ・平和でアガれます。", checkpoint: "宣言できるかと、宣言すべきかを分けます。" }),
  question({ id: "b-partial-yaku", difficulty: "beginner", category: "yaku", title: "白なら役あり、8萬なら？", hand: riichiHands.yakuhai, turn: 8, recommendedAction: "riichi", confidence: "high",
    explanation: "白・8萬のシャンポン待ち。白でロンなら白の役がありますが、8萬でロンすると白は雀頭になり、役がありません。リーチなら両方でロンできるため、この平場ではリーチを推奨します。", checkpoint: "待ち牌ごとに成立する役を確認します。" }),

  question({ id: "m-early-change", difficulty: "intermediate", category: "shape", title: "序盤の役なしカンチャン", hand: riichiHands.kanchan, turn: 3, wallTilesRemaining: 56, recommendedAction: "dama",
    context: "3巡目で、手変わりを待って形を改善することを優先する練習です。他家のリーチ・副露はありません。",
    explanation: "今は4萬だけの役なしカンチャンです。例えば6萬を引いて3萬を切れば、4萬・7萬の両面に変化できます。今回は序盤の改善余地を重視してダマ寄り。即リーチも候補で、期待値上の唯一解ではありません。", checkpoint: "手変わりを待つなら、どのツモでどの牌を切るかまで考えます。" }),
  question({ id: "m-late-no-yaku", difficulty: "intermediate", category: "yaku", title: "同じ手でも11巡目なら", hand: riichiHands.kanchan, turn: 11, wallTilesRemaining: 24, recommendedAction: "riichi",
    explanation: "序盤例と同じ役なしカンチャンですが、今回は11巡目。手変わりを待つ時間が減り、ダマのままでは通常のロンができません。現在のテンパイでアガリを目指すリーチ寄りとします。", checkpoint: "手変わりの価値は残り巡目と一緒に評価します。" }),
  question({ id: "m-low-follow", difficulty: "intermediate", category: "defense", title: "親リーチに安い手で追う？", hand: riichiHands.pinfu, turn: 12, wallTilesRemaining: 20, scores: [24000, 35000, 25000, 15000], opponentRiichi: "東", riichiSticks: 1, recommendedAction: "dama",
    context: "子のトップで、親が先制リーチ。候補の中は親の現物です。宣言牌を切れる前提で、その後も手を固定してよいかを考えます。", discard: "中", rivers: { 東: ["中", "9m"] },
    explanation: "宣言牌の中は親に通せますが、リーチ後は次の危険牌でも原則ツモ切りになります。自分のダマは平和1,000点。リードを守る目的では、ダマでロンを待ち、危険牌にはテンパイを崩せる選択を残します。", checkpoint: "今切る牌が安全でも、リーチ後の全てのツモが安全とは限りません。" }),
  question({ id: "m-dora-one", difficulty: "intermediate", category: "value", title: "ドラ1の両面を育てる", hand: riichiHands.ryanmen, doraIndicator: "3p", turn: 7, recommendedAction: "riichi",
    explanation: "タンヤオ・平和・ドラ1でダマ3,900点、リーチで7,700点です。7巡目の両面で、特別な終了条件がない平場。追加の1翻が大きな点差を生むリーチ寄りとします。", checkpoint: "翻が1増えたとき、必ず同じ割合で点数が増えるわけではありません。" }),
  question({ id: "m-mangan", difficulty: "intermediate", category: "value", title: "ダマ満貫の柔軟性", hand: riichiHands.high, doraIndicator: "5s", turn: 12, recommendedAction: "dama",
    context: "12巡目の平場。すでに高打点があるため、ロン機会と他家の動きへの対応を重視する練習です。他家のリーチはありません。",
    explanation: "ダマで8,000点、リーチで12,000点です。リーチの加点は魅力ですが、今回は十分な打点と終盤の柔軟性を重視してダマ寄り。跳満を狙うリーチも有力で、どちらの期待値が高いかは計算していません。", checkpoint: "満貫と跳満の差を認識したうえで、柔軟性を選ぶ理由を言葉にします。" }),
  question({ id: "m-pairs-dora", difficulty: "intermediate", category: "shape", title: "ドラ2の七対子を知らせない", hand: riichiHands.pairs, doraIndicator: "6p", turn: 12, recommendedAction: "dama",
    context: "単騎の七対子。12巡目で、打点をすでに確保し、待ちを伏せることを重視する練習です。他家のリーチはありません。",
    explanation: "ダマの七対子・ドラ2でロン6,400点。リーチなら8,000点になりますが、今回は加点よりも単騎のロン機会と、別の単騎へ変える余地を重視してダマ寄りとします。", checkpoint: "七対子の単騎変更は、宣言前なら可能です。ただし新しい牌の安全度と枚数も見ます。" }),
  question({ id: "m-partial", difficulty: "intermediate", category: "yaku", title: "シャンポン両方をアガリ牌に", hand: riichiHands.yakuhai, turn: 10, rivers: { 西: ["白"] }, recommendedAction: "riichi",
    explanation: "白の残り枚数が減っていても、8萬で役なしになる問題は残ります。リーチを加えると8萬でもロンできます。待ちの全体をアガリ牌として使う目的で、今回はリーチ寄りです。", checkpoint: "役のある側の枚数だけでなく、役なし側にリーチで役を付ける価値も確認します。" }),
  question({ id: "m-visible", difficulty: "intermediate", category: "defense", title: "両面でも待ちが見えている", hand: riichiHands.ryanmen, turn: 14, wallTilesRemaining: 12, scores: [24000, 36000, 23000, 16000], opponentRiichi: "東", riichiSticks: 1, rivers: { 東: ["中", "3m", "6m"], 西: ["3m", "6m"] }, recommendedAction: "dama",
    context: "子のトップで親リーチを受けています。候補の中は親の現物。3萬・6萬は公開した河に2枚ずつ見えています。",
    explanation: "両面でも、表示した河を差し引くと待ちの上限は合計4枚。終盤かつ親リーチに対し、ダマ2,000点で守備への選択を残すことを推奨します。4枚は山の実残数ではありません。", checkpoint: "『両面だから8枚』と固定せず、公開牌を引きます。" }),
  question({ id: "m-sanshoku", difficulty: "intermediate", category: "value", title: "カンチャンの三色を満貫に", hand: riichiHands.sanshoku, turn: 6, recommendedAction: "riichi",
    explanation: "3萬待ちでダマ5,200点、リーチなら8,000点です。6巡目の平場で打点を取りに行くリーチ寄り。カンチャンなので待ちの狭さは残り、リーチで待ち自体が広くなるわけではありません。", checkpoint: "打点の改善と、待ちの改善を区別します。" }),
  question({ id: "m-penchan", difficulty: "intermediate", category: "value", title: "ペンチャン三色の打点差", hand: riichiHands.penchan, turn: 7, recommendedAction: "riichi",
    explanation: "3筒のペンチャンですが、アガると三色同順があります。ダマ2,600点に対しリーチ5,200点。今回は平場で追加打点を狙うリーチ寄りです。悪い待ちなら全てダマ、とは決めません。", checkpoint: "待ちの種類だけでなく、現在の役と加点幅も見ます。" }),

  question({ id: "a-direct", difficulty: "advanced", category: "conditions", title: "トップ直撃の必要打点", hand: riichiHands.ryanmen, roundWind: "南", roundNumber: 4, turn: 9, scores: [32000, 27000, 22000, 19000], targetRank: 1, recommendedAction: "riichi",
    context: "オーラス・自分は2着の子。目標はトップ。他家のリーチはありません。同点は目標達成に含めません。",
    explanation: "ダマ2,000点のトップ直撃では、自分29,000点・東家30,000点で届きません。リーチ3,900点の直撃なら自分30,900点・東家28,100点で逆転します。ここでは条件を満たす打点を作るリーチ寄りです。", checkpoint: "点差の全額を稼ぐ必要はありません。直撃なら相手の点棒も減ります。" }),
  question({ id: "a-top", difficulty: "advanced", category: "conditions", title: "同じ手でトップなら", hand: riichiHands.ryanmen, roundWind: "南", roundNumber: 4, turn: 9, scores: [27000, 32000, 22000, 19000], targetRank: 1, recommendedAction: "dama",
    context: "オーラス・自分はトップの子。自分のアガリで終了。トップ維持を優先します。他家のリーチはありません。",
    explanation: "直撃条件の問題と同じ牌姿でも、今回はどこからダマでアガってもトップです。リーチで増やす点数より、ダマのロン機会と次の危険牌への対応を優先します。", checkpoint: "同じ牌姿でも、目的が逆転か維持かで推奨は変わります。" }),
  question({ id: "a-second", difficulty: "advanced", category: "conditions", title: "2着を確保するなら", hand: riichiHands.ryanmen, roundWind: "南", roundNumber: 4, turn: 11, scores: [35000, 24500, 25000, 15500], targetRank: 2, recommendedAction: "dama",
    context: "オーラス・自分は3着の子。目標は2着以上で終了することです。他家のリーチはありません。",
    explanation: "ダマの2,000点をどの相手からロンしても2着以上になり、ツモでも条件を満たします。今回は2着確保が目的なので、リーチの追加打点よりダマのままアガれる価値を優先します。", checkpoint: "トップ狙いと2着確保は、別の条件として計算します。" }),
  question({ id: "a-no-yaku-top", difficulty: "advanced", category: "yaku", title: "トップでも役なしなら", hand: riichiHands.kanchan, roundWind: "南", roundNumber: 4, turn: 11, scores: [27000, 32000, 22000, 19000], targetRank: 1, recommendedAction: "riichi",
    context: "オーラス・子のトップ。自分のアガリで終了します。他家のリーチはありません。",
    explanation: "トップだからダマ、と機械的には選べません。今回は役なしカンチャンで、ダマのロンはできません。ツモや手変わり待ちも選択肢ですが、今のテンパイで局を終える機会を増やすリーチ寄りです。", checkpoint: "ダマの速度を優先できるのは、ダマでアガれる役があるときです。" }),
  question({ id: "a-haneman-needed", difficulty: "advanced", category: "conditions", title: "満貫と跳満の条件差", hand: riichiHands.high, doraIndicator: "5s", roundWind: "南", roundNumber: 4, turn: 10, scores: [35000, 24000, 23000, 18000], targetRank: 1, recommendedAction: "riichi",
    context: "オーラス・子の2着。トップを目指し、トップ以外からのロンも考えます。他家のリーチはありません。",
    explanation: "ダマ満貫を西家・北家からロンしても自分32,000点で、東家35,000点に届きません。リーチ跳満なら自分36,000点となり逆転します。トップ直撃だけでなく、どこからでも条件を満たす打点を狙うリーチ寄りです。", checkpoint: "条件を満たせる放銃者が増えることも、打点を上げる理由になります。" }),
  question({ id: "a-mangan-enough", difficulty: "advanced", category: "conditions", title: "満貫でどこからでも逆転", hand: riichiHands.high, doraIndicator: "5s", roundWind: "南", roundNumber: 4, turn: 10, scores: [33000, 28000, 21000, 18000], targetRank: 1, recommendedAction: "dama",
    context: "オーラス・子の2着。目標はトップです。他家のリーチはありません。",
    explanation: "今回はダマ満貫で、どこからのロンでもツモでもトップになります。前の跳満条件の問題とは点棒が違います。すでに必要打点があるため、追加点よりアガリ機会と柔軟性を優先するダマ寄りです。", checkpoint: "満貫ならダマという暗記ではなく、実際の4人の点棒を比べます。" }),
  question({ id: "a-furiten", difficulty: "advanced", category: "shape", title: "フリテンをリーチで解消できる？", hand: riichiHands.ryanmen, turn: 6, rivers: { 南: ["3m"] }, recommendedAction: "dama",
    context: "自分の河に3萬があります。6巡目で、フリテンを解消できる手変わりを探すことを優先する練習です。他家のリーチはありません。",
    explanation: "3萬を捨てているため、6萬でもロンできないフリテンです。リーチしても解消しません。今回は手変わりの選択を残すダマ寄り。例えば7萬を引いて4萬を切れば6萬のカンチャン待ちとなり、河によるフリテンを解消できます。ただし待ちは狭くなり、見逃しによるフリテンも別途確認が必要です。", checkpoint: "フリテンリーチはルール上可能でも、現在のロン不能は変わりません。" }),
  question({ id: "a-pairs-defense", difficulty: "advanced", category: "defense", title: "終盤の七対子と親リーチ", hand: riichiHands.pairs, turn: 14, wallTilesRemaining: 12, scores: [24000, 35000, 25000, 15000], opponentRiichi: "東", riichiSticks: 1, rivers: { 東: ["中", "9m"] }, recommendedAction: "dama",
    context: "子のトップで親リーチを受けています。候補の中は親の現物。失点を避けることを優先します。",
    explanation: "七対子の単騎で、ダマ1,600点・リーチ3,200点。今回は終盤かつトップで親リーチを受けており、リーチ後のツモ切り固定を避けます。ダマでテンパイを維持しつつ、次に危険牌を引けば守備へ移る余地を残します。", checkpoint: "待ちの見た目だけでなく、巡目・順位・相手のリーチを合わせて判断します。" }),
  question({ id: "a-follow-goal", difficulty: "advanced", category: "conditions", title: "先制リーチ相手の直撃条件", hand: riichiHands.ryanmen, doraIndicator: "3p", roundWind: "南", roundNumber: 4, turn: 11, wallTilesRemaining: 24, scores: [34000, 24000, 23000, 18000], targetRank: 1, opponentRiichi: "東", riichiSticks: 1, rivers: { 東: ["中", "9m"] }, recommendedAction: "riichi",
    context: "オーラス・子の2着からトップを目指します。東家がリーチし、その1,000点はすでに東家の点棒から引いてあります。候補の中は東家の現物です。",
    explanation: "ダマ3,900点の東家直撃に既存の供託1,000点を加えても、自分28,900点・東家30,100点で届きません。リーチ7,700点の直撃なら、自分32,700点・東家26,300点で逆転します。ここでは逆転に必要な打点を取るリーチ寄りです。", checkpoint: "供託は放銃者の点棒ではありません。既存の供託と自分の新しいリーチ棒を分けます。" }),
  question({ id: "a-shanpon-lead", difficulty: "advanced", category: "defense", title: "シャンポンでも役は両方ある", hand: riichiHands.shanpon, roundWind: "南", roundNumber: 3, turn: 13, wallTilesRemaining: 16, scores: [24000, 40000, 20000, 15000], opponentRiichi: "東", riichiSticks: 1, rivers: { 東: ["中", "9m"] }, recommendedAction: "dama",
    context: "子の大きなトップ。親リーチを受け、候補の中は親の現物です。失点回避を優先します。",
    explanation: "2筒・8萬のどちらにもタンヤオがあり、ダマでロンできます。今は大きなリードを守る局面なので、1,300点を2,600点にするために手を固定せず、次の危険牌に対応できるダマ寄りです。", checkpoint: "役牌シャンポンの片アガリと、タンヤオの両アガリを区別します。" })
];

export const riichiRepresentativeIds = ["b-ryanmen", "b-partial-yaku", "m-early-change", "a-direct", "a-furiten"];
